apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus-1
      type: prometheus
      access: proxy
      orgId: 1
      url: http://eod-monitoring-prometheus-server.monitoring
      isDefault: true
      version: 1
      editable: true