{
 "title": "Flink Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "deployment_name", "query": "label_values(deployment_name)" },
   {
    "name": "operator_name",
    "query": "label_values({deployment_name=\"$deployment_name\"}, operator_name)"
   }
  ]
 },
 "panels": [
  { "title": "Job Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Completed Checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Failed Checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Full Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_job_fullRestarts{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Restart Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_job_restartingTime{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Total Task Manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Task slots Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Task slots total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  { "title": "Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Records In Total",
   "type": "singlestat",
   "description": "Sum of  records in for the operator",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsIn{deployment_name=\"$deployment_name\", operator_name=\"$operator_name\"})",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Records Out Total",
   "type": "singlestat",
   "description": "Sum of  records out for the operator",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOut{deployment_name=\"$deployment_name\", operator_name=\"$operator_name\"})",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Task Operator Avg. Commit Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_commit_latency_avg{deployment_name=\"$deployment_name\", operator_name=\"$operator_name\"}"
    }
   ]
  },
  {
   "title": "Rate of Records In per Sec",
   "type": "graph",
   "description": "Rate of records in per second in  to the taskmanager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Number of records" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Rate of Records Out per Sec",
   "type": "graph",
   "description": "Rate of records out per second in  from the taskmanager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of records" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsOutPerSecond{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  { "title": "Job Resource Use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Job Manager CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Job Manager Heap Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max{deployment_name=\"$deployment_name\"}",
     "legendFormat": "Heap max"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{deployment_name=\"$deployment_name\"}",
     "legendFormat": "Heap used"
    }
   ]
  },
  {
   "title": "Task Manager CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load{deployment_name=\"$deployment_name\"}"
    }
   ]
  },
  {
   "title": "Task Manager Heap Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max{deployment_name=\"$deployment_name\"}",
     "legendFormat": "Heap max"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{deployment_name=\"$deployment_name\"}",
     "legendFormat": "Heap used"
    }
   ]
  }
 ]
}