# code from - https://sysdig.com/blog/prometheus-metrics/
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-test-go-client
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: prometheus-test-go-client
      image: tinkal/prometheus-go-client
      ports:
        - containerPort: 8080
