cp-zookeeper:
  servers: 1
  prometheus:
    jmx:
      enabled: false

cp-kafka:
  brokers: 1
  prometheus:
    jmx:
      enabled: false

cp-schema-registry:
    enabled: true
    prometheus:
      jmx:
        enabled: true

cp-kafka-rest:
    enabled: true
    cp-zookeeper:
        url: "my-confluent-oss-cp-zookeeper-headless.kafka:2181"
    cp-schema-registry:
        url: "my-confluent-oss-cp-schema-registry.kafka:8081"
    external:
        enabled: true
        type: NodePort #can't specify a specific nodePort, its random
    prometheus:
        jmx:
            enabled: true

cp-kafka-connect: 
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false
  prometheus:
    jmx:
      enabled: false
